version: '2'
services:
  zookeeper:
    image: bitnami/zookeeper:3.7
    container_name: zookeeper
    hostname: zoo1
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    logging:
      driver: none

  kafka:
    image: bitnami/kafka:2.8.0
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
#      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
#      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
#    logging:
#      driver: none

  player:
    build: .
    volumes:
      - .:/home/usr/app
    depends_on:
      - kafka